apiVersion: v1
kind: Service
metadata:
  name: ice-classification-service
  labels:
    app: ice-classification
spec:
  selector:
    app: ice-classification
  ports:
    - protocol: TCP
      port: 80          # Port exposé dans le cluster
      targetPort: 8888  # Port du conteneur (celui du notebook ou app)
